/* 답변 */
drop table ANSWER cascade constraints;
CREATE TABLE ANSWER (
	ANSWER_NO NUMBER NOT NULL, /* 답변번호 */
	ANSWER_CONTENT CLOB NOT NULL, /* 답변내용 */
	ANSWER_REGDATE DATE DEFAULT sysdate NOT NULL, /* 작성일 */
	QUESTION_NO NUMBER /* 문의글번호 */
);

COMMENT ON TABLE ANSWER IS '답변';

COMMENT ON COLUMN ANSWER.ANSWER_NO IS '답변번호';

COMMENT ON COLUMN ANSWER.ANSWER_CONTENT IS '답변내용';

COMMENT ON COLUMN ANSWER.ANSWER_REGDATE IS '작성일';

COMMENT ON COLUMN ANSWER.QUESTION_NO IS '문의글번호';

CREATE UNIQUE INDEX PK_ANSWER
	ON ANSWER (
		ANSWER_NO ASC
	);

CREATE UNIQUE INDEX PK_ANSWER
	ON ANSWER (
		ANSWER_NO ASC
	);

ALTER TABLE ANSWER
	ADD
		CONSTRAINT PK_ANSWER
		PRIMARY KEY (
			ANSWER_NO
		);

create sequence ANSWER_seq
start with 1
increment by 1
nocache;	

create or replace view answerView
as
select a.*,q.user_no,q.project_no
from ANSWER a join QUESTION q
on a.QUESTION_NO=q.QUESTION_NO;

/* 창작자문의하기 */
drop table QUESTION cascade constraints;
CREATE TABLE QUESTION (
	QUESTION_NO NUMBER NOT NULL, /* 문의글번호 */
	QUESTION_TITLE VARCHAR2(100) NOT NULL, /* 문의제목 */
	QUESTION_CONTENT CLOB NOT NULL, /* 문의내용 */
	QUESTION_FLAG CHAR NOT NULL, /* 답변여부 */
	QUESTION_REGDATE DATE DEFAULT sysdate NOT NULL, /* 작성일 */
	USER_NO NUMBER, /* 회원번호 */
	PROJECT_NO NUMBER /* 프로젝트번호 */

);

/* QUESTION_FLAG 디폴트값 추가 */
alter table QUESTION modify QUESTION_FLAG CHAR default 'N';

COMMENT ON TABLE QUESTION IS '창작자문의하기';

COMMENT ON COLUMN QUESTION.QUESTION_NO IS '문의글번호';

COMMENT ON COLUMN QUESTION.QUESTION_TITLE IS '문의제목';

COMMENT ON COLUMN QUESTION.QUESTION_CONTENT IS '문의내용';

COMMENT ON COLUMN QUESTION.QUESTION_FLAG IS '답변여부';

COMMENT ON COLUMN QUESTION.QUESTION_REGDATE IS '작성일';

COMMENT ON COLUMN QUESTION.PROJECT_NO IS '프로젝트번호';

CREATE UNIQUE INDEX PK_QUESTION
	ON QUESTION (
		QUESTION_NO ASC
	);

ALTER TABLE QUESTION
	ADD
		CONSTRAINT PK_QUESTION
		PRIMARY KEY (
			QUESTION_NO
		);

ALTER TABLE QUESTION
	ADD
		CONSTRAINT FK_PROJECT_TO_QUESTION
		FOREIGN KEY (
			PROJECT_NO
		)
		REFERENCES PROJECT (
			PROJECT_NO
		);

ALTER TABLE QUESTION
	ADD
		CONSTRAINT FK_USERS_TO_QUESTION
		FOREIGN KEY (
			USER_NO
		)
		REFERENCES USERS (
			USER_NO
		);

create sequence QUESTION_seq
start with 1
increment by 1
nocache;

create sequence messageno_seq
start with 1
increment by 1
nocache;

create or replace view messageView
as
select r.*,s.user_no
from MESSAGE_RECEIVE r join MESSAGE_SEND s
on r.MESSAGE_NO=s.MESSAGE_NO;

/* 쪽지발신 */
drop table MESSAGE_SEND cascade constraints;
CREATE TABLE MESSAGE_SEND (
	MESSAGE_NO NUMBER NOT NULL, /* 번호 */
	MESSAGE_TITLE VARCHAR2(100) NOT NULL, /* 제목 */
	MESSAGE_CONTENT CLOB NOT NULL, /* 내용 */
	MESSAGE_REGDATE DATE DEFAULT sysdate NOT NULL, /* 작성일 */
	USER_NO NUMBER /* 회원번호 */
);

COMMENT ON TABLE MESSAGE_SEND IS '쪽지발신';

COMMENT ON COLUMN MESSAGE_SEND.MESSAGE_NO IS '번호';

COMMENT ON COLUMN MESSAGE_SEND.MESSAGE_TITLE IS '제목';

COMMENT ON COLUMN MESSAGE_SEND.MESSAGE_CONTENT IS '내용';

COMMENT ON COLUMN MESSAGE_SEND.MESSAGE_REGDATE IS '작성일';

COMMENT ON COLUMN MESSAGE_SEND.USER_NO IS '회원번호';

CREATE UNIQUE INDEX PK_MESSAGE_SEND
	ON MESSAGE_SEND (
		MESSAGE_NO ASC
	);

ALTER TABLE MESSAGE_SEND
	ADD
		CONSTRAINT PK_MESSAGE_SEND
		PRIMARY KEY (
			MESSAGE_NO
		);

ALTER TABLE MESSAGE_SEND
	ADD
CONSTRAINT FK_USERS_TO_MESSAGE_SEND
FOREIGN KEY (
	USER_NO
)
REFERENCES USERS (
	USER_NO
);

/* 쪽지수신 */
drop table MESSAGE_RECEIVE cascade constraints;
CREATE TABLE MESSAGE_RECEIVE (
	MESSAGE_NO NUMBER NOT NULL, /* 번호 */
	MESSAGE_TITLE VARCHAR2(100), /* 제목 */
	MESSAGE_CONTENT CLOB, /* 내용 */
	MESSAGE_REGDATE DATE DEFAULT sysdate NOT NULL /* 작성일 */
);

COMMENT ON TABLE MESSAGE_RECEIVE IS '쪽지수신';

COMMENT ON COLUMN MESSAGE_RECEIVE.MESSAGE_NO IS '번호';

COMMENT ON COLUMN MESSAGE_RECEIVE.MESSAGE_TITLE IS '제목';

COMMENT ON COLUMN MESSAGE_RECEIVE.MESSAGE_CONTENT IS '내용';

COMMENT ON COLUMN MESSAGE_RECEIVE.MESSAGE_REGDATE IS '작성일';

CREATE UNIQUE INDEX PK_MESSAGE_RECEIVE
	ON MESSAGE_RECEIVE (
		MESSAGE_NO ASC
	);

ALTER TABLE MESSAGE_RECEIVE
	ADD
		CONSTRAINT PK_MESSAGE_RECEIVE
		PRIMARY KEY (
			MESSAGE_NO
		);


ALTER TABLE MESSAGE_RECEIVE
	ADD
		CONSTRAINT FK_SEND_TO_RECEIVE
		FOREIGN KEY (
			MESSAGE_NO
		)
		REFERENCES MESSAGE_SEND (
			MESSAGE_NO
		);




