--------------------------------------------------------
--  파일이 생성됨 - 수요일-8월-11-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BOARD2
--------------------------------------------------------

  CREATE TABLE "HERB"."BOARD2" 
   (	"BOARD_NO" NUMBER, 
	"BOARD_TITLE" VARCHAR2(100 BYTE), 
	"BOARD_CONTENT" VARCHAR2(200 BYTE), 
	"BOARD_FILENAME" VARCHAR2(100 BYTE), 
	"BOARD_OLDFILENAME" VARCHAR2(100 BYTE), 
	"BOARD_FILESIZE" LONG, 
	"BOARD_DOWNCOUNT" NUMBER DEFAULT 0, 
	"BOARD_REGDATE" DATE DEFAULT sysdate, 
	"BOARD_READCOUNT" NUMBER DEFAULT 0, 
	"USER_NICKNAME" VARCHAR2(50 BYTE), 
	"DELFLAG" VARCHAR2(30 BYTE) DEFAULT 'N'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HERBMALL" ;

   COMMENT ON TABLE "HERB"."BOARD2"  IS '게시판';
--------------------------------------------------------
--  DDL for Index PK_BOARD2
--------------------------------------------------------

  CREATE UNIQUE INDEX "HERB"."PK_BOARD2" ON "HERB"."BOARD2" ("BOARD_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HERBMALL" ;
--------------------------------------------------------
--  Constraints for Table BOARD2
--------------------------------------------------------

  ALTER TABLE "HERB"."BOARD2" ADD CONSTRAINT "PK_BOARD2" PRIMARY KEY ("BOARD_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HERBMALL"  ENABLE;
  ALTER TABLE "HERB"."BOARD2" MODIFY ("BOARD_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "HERB"."BOARD2" MODIFY ("BOARD_TITLE" NOT NULL ENABLE);
  ALTER TABLE "HERB"."BOARD2" MODIFY ("BOARD_NO" NOT NULL ENABLE);
