--------------------------------------------------------
--  파일이 생성됨 - 수요일-8월-11-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table COMMENTS
--------------------------------------------------------

  CREATE TABLE "HERB"."COMMENTS" 
   (	"COMMENT_NO" NUMBER, 
	"COMMENT_CONTENT" CLOB, 
	"COMMENT_REGDATE" DATE, 
	"COMMENT_GROUPNO" NUMBER, 
	"COMMENT_STEP" NUMBER DEFAULT 0, 
	"COMMENT_SORTNO" NUMBER DEFAULT 0, 
	"COMMENT_DELFLAG" VARCHAR2(50 BYTE) DEFAULT 'N', 
	"BOARD_NO" NUMBER, 
	"USER_NICKNAME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HERBMALL" 
 LOB ("COMMENT_CONTENT") STORE AS BASICFILE (
  TABLESPACE "HERBMALL" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "HERB"."COMMENTS"."COMMENT_NO" IS '댓글번호';
   COMMENT ON COLUMN "HERB"."COMMENTS"."COMMENT_CONTENT" IS '내용';
   COMMENT ON COLUMN "HERB"."COMMENTS"."COMMENT_REGDATE" IS '작성일';
   COMMENT ON COLUMN "HERB"."COMMENTS"."COMMENT_GROUPNO" IS '그룹';
   COMMENT ON COLUMN "HERB"."COMMENTS"."COMMENT_STEP" IS '스텝';
   COMMENT ON COLUMN "HERB"."COMMENTS"."COMMENT_SORTNO" IS '정렬';
   COMMENT ON COLUMN "HERB"."COMMENTS"."COMMENT_DELFLAG" IS '삭제여부';
   COMMENT ON COLUMN "HERB"."COMMENTS"."BOARD_NO" IS '게시글번호';
   COMMENT ON COLUMN "HERB"."COMMENTS"."USER_NICKNAME" IS '회원번호';
   COMMENT ON TABLE "HERB"."COMMENTS"  IS '댓글';
--------------------------------------------------------
--  DDL for Index PK_COMMENTS
--------------------------------------------------------

  CREATE UNIQUE INDEX "HERB"."PK_COMMENTS" ON "HERB"."COMMENTS" ("COMMENT_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HERBMALL" ;
--------------------------------------------------------
--  Constraints for Table COMMENTS
--------------------------------------------------------

  ALTER TABLE "HERB"."COMMENTS" ADD CONSTRAINT "PK_COMMENTS" PRIMARY KEY ("COMMENT_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HERBMALL"  ENABLE;
  ALTER TABLE "HERB"."COMMENTS" MODIFY ("COMMENT_REGDATE" NOT NULL ENABLE);
  ALTER TABLE "HERB"."COMMENTS" MODIFY ("COMMENT_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "HERB"."COMMENTS" MODIFY ("COMMENT_NO" NOT NULL ENABLE);
